#pragma once

/*
* The halo 1 AI port's own headers, in the order halo 1's sources included them.
*/

#include "h1_ai_declarations.h"
#include "h1_ai_engine.h"
#include "h1_ai_cseries.h"

// halo 1's engine types the AI reads (halo 1's layouts: the port's mirrors of carto's objects, the cache file's tags)
#include "engine/objects/object_types.h"
#include "engine/objects/damage_resistances.h"
#include "engine/models/model_definitions.h"
#include "engine/models/model_animation_definitions.h"
#include "engine/models/models.h"
#include "engine/sound/sound_definitions.h"
#include "engine/objects/object_definitions.h"
#include "engine/physics/collision_usage.h"
#include "engine/physics/collision_model_definitions.h"
#include "engine/physics/breakable_surfaces.h"
#include "engine/objects/objects.h"
#include "engine/units/unit_definitions.h"
#include "engine/units/biped_definitions.h"
#include "engine/units/vehicle_definitions.h"
#include "engine/units/dialogue_definitions.h"
#include "engine/game/aim_assist.h"
#include "engine/items/item_definitions.h"
#include "engine/items/weapon_definitions.h"
#include "engine/items/projectile_definitions.h"
#include "engine/items/equipment_definitions.h"
#include "engine/devices/device_definitions.h"
#include "engine/game/game_globals.h"
#include "engine/objects/damage_effect_definitions.h"
#include "engine/hs/object_lists.h"
#include "engine/game/game.h"
#include "engine/game/game_allegiance.h"
#include "ai.h"
#include "engine/units/unit_control_data.h"
#include "engine/units/units.h"
#include "engine/units/bipeds.h"
#include "engine/units/vehicles.h"
#include "engine/units/vehicle_datum.h"
#include "engine/items/items.h"
#include "engine/items/weapons.h"
#include "engine/items/projectiles.h"
#include "engine/physics/bsp2d.h"
#include "engine/physics/bsp3d.h"
#include "engine/physics/collision_bsp_definitions.h"
#include "h1_ai_render_types.h"
#include "engine/structures/leaf_map.h"
#include "engine/structures/structure_bsp_definitions.h"
#include "engine/physics/collision_bsp.h"
#include "engine/physics/collisions.h"
#include "engine/physics/collision_features.h"
#include "engine/physics/collision_models.h"
#include "engine/physics/physics_definitions.h"
#include "engine/physics/physics.h"
#include "engine/scenario/fog_definitions.h"
#include "engine/objects/damage.h"
#include "engine/devices/devices.h"
#include "h1_ai_engine_functions.h"

#include "ai_constants.h"
#include "ai_globals.h"
#include "actor_definitions.h"
#include "ai_scenario_definitions.h"
#include "actor_types.h"
#include "actor_type_definitions.h"
#include "path.h"
#include "path_structure_bsp.h"
#include "actions.h"
#include "props.h"
#include "actors.h"
#include "encounters.h"
#include "ai.h"
#include "ai_communication.h"
#include "ai_script.h"
#include "actor_placement.h"
#include "actor_activation.h"
#include "ai_debug.h"
#include "ai_debug_scripting.h"
#include "ai_profile.h"
