// generated by tools/hs_inl_gen.py, do not edit

static const int16 k_hs_parameters_27[] = { _hs_type_boolean };
static const int16 k_hs_parameters_28[] = { _hs_type_string };
static const int16 k_hs_parameters_30[] = { _hs_type_trigger_volume, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_31[] = { _hs_type_trigger_volume, _hs_type_object };
static const int16 k_hs_parameters_32[] = { _hs_type_trigger_volume, _hs_type_object_list };
static const int16 k_hs_parameters_33[] = { _hs_type_trigger_volume, _hs_type_object_list };
static const int16 k_hs_parameters_34[] = { _hs_type_object, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_35[] = { _hs_type_object, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_36[] = { _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_37[] = { _hs_type_object, _hs_type_string, _hs_type_string };
static const int16 k_hs_parameters_38[] = { _hs_type_object_name };
static const int16 k_hs_parameters_39[] = { _hs_type_object };
static const int16 k_hs_parameters_40[] = { _hs_type_object_name };
static const int16 k_hs_parameters_41[] = { _hs_type_string };
static const int16 k_hs_parameters_42[] = { _hs_type_string };
static const int16 k_hs_parameters_43[] = { _hs_type_string };
static const int16 k_hs_parameters_45[] = { _hs_type_object_list, _hs_type_short_integer };
static const int16 k_hs_parameters_46[] = { _hs_type_object_list };
static const int16 k_hs_parameters_47[] = { _hs_type_effect, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_48[] = { _hs_type_effect, _hs_type_object, _hs_type_string };
static const int16 k_hs_parameters_49[] = { _hs_type_damage, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_50[] = { _hs_type_damage, _hs_type_object };
static const int16 k_hs_parameters_51[] = { _hs_type_object_list, _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_52[] = { _hs_type_object_list, _hs_type_cutscene_flag, _hs_type_real };
static const int16 k_hs_parameters_53[] = { _hs_type_object_definition };
static const int16 k_hs_parameters_54[] = { _hs_type_string, _hs_type_real };
static const int16 k_hs_parameters_55[] = { _hs_type_string };
static const int16 k_hs_parameters_58[] = { _hs_type_string };
static const int16 k_hs_parameters_59[] = { _hs_type_short_integer, _hs_type_short_integer };
static const int16 k_hs_parameters_60[] = { _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_61[] = { _hs_type_long_integer, _hs_type_boolean };
static const int16 k_hs_parameters_62[] = { _hs_type_short_integer };
static const int16 k_hs_parameters_65[] = { _hs_type_boolean };
static const int16 k_hs_parameters_66[] = { _hs_type_unit, _hs_type_cutscene_recording };
static const int16 k_hs_parameters_67[] = { _hs_type_unit, _hs_type_cutscene_recording };
static const int16 k_hs_parameters_68[] = { _hs_type_vehicle, _hs_type_cutscene_recording };
static const int16 k_hs_parameters_69[] = { _hs_type_unit };
static const int16 k_hs_parameters_70[] = { _hs_type_unit };
static const int16 k_hs_parameters_71[] = { _hs_type_object, _hs_type_boolean };
static const int16 k_hs_parameters_72[] = { _hs_type_object, _hs_type_boolean };
static const int16 k_hs_parameters_74[] = { _hs_type_object, _hs_type_boolean };
static const int16 k_hs_parameters_75[] = { _hs_type_object, _hs_type_real, _hs_type_short_integer };
static const int16 k_hs_parameters_76[] = { _hs_type_object, _hs_type_string, _hs_type_object, _hs_type_string };
static const int16 k_hs_parameters_77[] = { _hs_type_object, _hs_type_object };
static const int16 k_hs_parameters_79[] = { _hs_type_object_list };
static const int16 k_hs_parameters_80[] = { _hs_type_object_list };
static const int16 k_hs_parameters_81[] = { _hs_type_object, _hs_type_boolean };
static const int16 k_hs_parameters_82[] = { _hs_type_object_list };
static const int16 k_hs_parameters_83[] = { _hs_type_object_definition };
static const int16 k_hs_parameters_84[] = { _hs_type_object };
static const int16 k_hs_parameters_85[] = { _hs_type_object };
static const int16 k_hs_parameters_86[] = { _hs_type_cutscene_camera_point };
static const int16 k_hs_parameters_88[] = { _hs_type_boolean };
static const int16 k_hs_parameters_89[] = { _hs_type_scenery };
static const int16 k_hs_parameters_90[] = { _hs_type_scenery, _hs_type_animation_graph, _hs_type_string };
static const int16 k_hs_parameters_91[] = { _hs_type_scenery, _hs_type_animation_graph, _hs_type_string, _hs_type_short_integer };
static const int16 k_hs_parameters_92[] = { _hs_type_boolean };
static const int16 k_hs_parameters_93[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_94[] = { _hs_type_unit };
static const int16 k_hs_parameters_95[] = { _hs_type_unit };
static const int16 k_hs_parameters_96[] = { _hs_type_unit };
static const int16 k_hs_parameters_97[] = { _hs_type_unit };
static const int16 k_hs_parameters_98[] = { _hs_type_unit };
static const int16 k_hs_parameters_99[] = { _hs_type_unit };
static const int16 k_hs_parameters_100[] = { _hs_type_unit, _hs_type_animation_graph, _hs_type_string, _hs_type_boolean, _hs_type_short_integer };
static const int16 k_hs_parameters_101[] = { _hs_type_unit, _hs_type_animation_graph, _hs_type_string, _hs_type_boolean };
static const int16 k_hs_parameters_102[] = { _hs_type_object_list, _hs_type_animation_graph, _hs_type_string, _hs_type_boolean };
static const int16 k_hs_parameters_103[] = { _hs_type_unit };
static const int16 k_hs_parameters_104[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_105[] = { _hs_type_unit, _hs_type_short_integer };
static const int16 k_hs_parameters_106[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_107[] = { _hs_type_unit, _hs_type_vehicle, _hs_type_string };
static const int16 k_hs_parameters_108[] = { _hs_type_vehicle, _hs_type_string, _hs_type_object_list };
static const int16 k_hs_parameters_109[] = { _hs_type_vehicle, _hs_type_string, _hs_type_unit };
static const int16 k_hs_parameters_110[] = { _hs_type_unit, _hs_type_string };
static const int16 k_hs_parameters_111[] = { _hs_type_unit };
static const int16 k_hs_parameters_112[] = { _hs_type_unit, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_113[] = { _hs_type_object_list, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_114[] = { _hs_type_unit, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_115[] = { _hs_type_object_list, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_116[] = { _hs_type_unit, _hs_type_string, _hs_type_object_list };
static const int16 k_hs_parameters_117[] = { _hs_type_unit, _hs_type_string };
static const int16 k_hs_parameters_118[] = { _hs_type_string };
static const int16 k_hs_parameters_119[] = { _hs_type_unit, _hs_type_string };
static const int16 k_hs_parameters_121[] = { _hs_type_unit };
static const int16 k_hs_parameters_122[] = { _hs_type_unit };
static const int16 k_hs_parameters_123[] = { _hs_type_unit };
static const int16 k_hs_parameters_124[] = { _hs_type_unit };
static const int16 k_hs_parameters_125[] = { _hs_type_unit };
static const int16 k_hs_parameters_126[] = { _hs_type_unit };
static const int16 k_hs_parameters_127[] = { _hs_type_unit, _hs_type_object_definition };
static const int16 k_hs_parameters_128[] = { _hs_type_unit, _hs_type_object_definition };
static const int16 k_hs_parameters_129[] = { _hs_type_object_list };
static const int16 k_hs_parameters_130[] = { _hs_type_object_list, _hs_type_boolean };
static const int16 k_hs_parameters_131[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_133[] = { _hs_type_object_list, _hs_type_boolean };
static const int16 k_hs_parameters_134[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_135[] = { _hs_type_unit };
static const int16 k_hs_parameters_136[] = { _hs_type_device, _hs_type_boolean };
static const int16 k_hs_parameters_137[] = { _hs_type_device };
static const int16 k_hs_parameters_138[] = { _hs_type_device, _hs_type_real };
static const int16 k_hs_parameters_139[] = { _hs_type_device, _hs_type_real };
static const int16 k_hs_parameters_140[] = { _hs_type_device };
static const int16 k_hs_parameters_141[] = { _hs_type_device, _hs_type_real };
static const int16 k_hs_parameters_142[] = { _hs_type_device_group };
static const int16 k_hs_parameters_143[] = { _hs_type_device_group, _hs_type_real };
static const int16 k_hs_parameters_144[] = { _hs_type_device_group, _hs_type_real };
static const int16 k_hs_parameters_145[] = { _hs_type_device, _hs_type_boolean };
static const int16 k_hs_parameters_146[] = { _hs_type_device, _hs_type_boolean };
static const int16 k_hs_parameters_147[] = { _hs_type_device_group, _hs_type_boolean };
static const int16 k_hs_parameters_154[] = { _hs_type_short_integer };
static const int16 k_hs_parameters_156[] = { _hs_type_ai };
static const int16 k_hs_parameters_157[] = { _hs_type_object_list };
static const int16 k_hs_parameters_158[] = { _hs_type_unit, _hs_type_ai };
static const int16 k_hs_parameters_159[] = { _hs_type_unit, _hs_type_actor_variant };
static const int16 k_hs_parameters_160[] = { _hs_type_unit };
static const int16 k_hs_parameters_161[] = { _hs_type_ai };
static const int16 k_hs_parameters_162[] = { _hs_type_ai };
static const int16 k_hs_parameters_163[] = { _hs_type_ai };
static const int16 k_hs_parameters_164[] = { _hs_type_ai };
static const int16 k_hs_parameters_166[] = { _hs_type_ai };
static const int16 k_hs_parameters_168[] = { _hs_type_ai };
static const int16 k_hs_parameters_169[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_170[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_171[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_172[] = { _hs_type_ai, _hs_type_ai };
static const int16 k_hs_parameters_173[] = { _hs_type_ai };
static const int16 k_hs_parameters_174[] = { _hs_type_ai, _hs_type_unit };
static const int16 k_hs_parameters_175[] = { _hs_type_ai };
static const int16 k_hs_parameters_176[] = { _hs_type_ai };
static const int16 k_hs_parameters_177[] = { _hs_type_ai };
static const int16 k_hs_parameters_178[] = { _hs_type_ai };
static const int16 k_hs_parameters_179[] = { _hs_type_ai };
static const int16 k_hs_parameters_180[] = { _hs_type_ai };
static const int16 k_hs_parameters_181[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_182[] = { _hs_type_ai, _hs_type_ai };
static const int16 k_hs_parameters_183[] = { _hs_type_ai, _hs_type_ai, _hs_type_string };
static const int16 k_hs_parameters_184[] = { _hs_type_object_list, _hs_type_ai };
static const int16 k_hs_parameters_185[] = { _hs_type_enum_team, _hs_type_enum_team };
static const int16 k_hs_parameters_186[] = { _hs_type_enum_team, _hs_type_enum_team };
static const int16 k_hs_parameters_187[] = { _hs_type_ai };
static const int16 k_hs_parameters_188[] = { _hs_type_ai };
static const int16 k_hs_parameters_189[] = { _hs_type_ai };
static const int16 k_hs_parameters_190[] = { _hs_type_ai };
static const int16 k_hs_parameters_191[] = { _hs_type_ai };
static const int16 k_hs_parameters_192[] = { _hs_type_ai };
static const int16 k_hs_parameters_193[] = { _hs_type_ai, _hs_type_unit, _hs_type_string };
static const int16 k_hs_parameters_194[] = { _hs_type_ai, _hs_type_unit, _hs_type_string };
static const int16 k_hs_parameters_195[] = { _hs_type_unit };
static const int16 k_hs_parameters_196[] = { _hs_type_ai };
static const int16 k_hs_parameters_197[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_198[] = { _hs_type_object_list, _hs_type_boolean };
static const int16 k_hs_parameters_199[] = { _hs_type_object_list, _hs_type_boolean };
static const int16 k_hs_parameters_200[] = { _hs_type_object_list, _hs_type_boolean };
static const int16 k_hs_parameters_201[] = { _hs_type_ai };
static const int16 k_hs_parameters_202[] = { _hs_type_ai };
static const int16 k_hs_parameters_203[] = { _hs_type_ai };
static const int16 k_hs_parameters_204[] = { _hs_type_ai };
static const int16 k_hs_parameters_205[] = { _hs_type_ai, _hs_type_ai };
static const int16 k_hs_parameters_206[] = { _hs_type_ai };
static const int16 k_hs_parameters_207[] = { _hs_type_ai, _hs_type_ai_command_list };
static const int16 k_hs_parameters_208[] = { _hs_type_unit, _hs_type_ai_command_list };
static const int16 k_hs_parameters_209[] = { _hs_type_ai };
static const int16 k_hs_parameters_210[] = { _hs_type_unit };
static const int16 k_hs_parameters_211[] = { _hs_type_object_list };
static const int16 k_hs_parameters_212[] = { _hs_type_ai };
static const int16 k_hs_parameters_213[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_214[] = { _hs_type_unit, _hs_type_boolean };
static const int16 k_hs_parameters_215[] = { _hs_type_ai, _hs_type_enum_ai_default_state };
static const int16 k_hs_parameters_216[] = { _hs_type_ai, _hs_type_enum_ai_default_state };
static const int16 k_hs_parameters_217[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_218[] = { _hs_type_ai };
static const int16 k_hs_parameters_220[] = { _hs_type_unit, _hs_type_ai };
static const int16 k_hs_parameters_221[] = { _hs_type_unit, _hs_type_real };
static const int16 k_hs_parameters_222[] = { _hs_type_unit, _hs_type_enum_team };
static const int16 k_hs_parameters_223[] = { _hs_type_unit, _hs_type_enum_actor_type };
static const int16 k_hs_parameters_224[] = { _hs_type_unit, _hs_type_ai };
static const int16 k_hs_parameters_225[] = { _hs_type_unit };
static const int16 k_hs_parameters_226[] = { _hs_type_unit, _hs_type_object };
static const int16 k_hs_parameters_227[] = { _hs_type_unit };
static const int16 k_hs_parameters_228[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_229[] = { _hs_type_ai };
static const int16 k_hs_parameters_230[] = { _hs_type_ai };
static const int16 k_hs_parameters_231[] = { _hs_type_ai, _hs_type_unit };
static const int16 k_hs_parameters_232[] = { _hs_type_ai, _hs_type_ai };
static const int16 k_hs_parameters_233[] = { _hs_type_ai, _hs_type_real };
static const int16 k_hs_parameters_234[] = { _hs_type_conversation };
static const int16 k_hs_parameters_235[] = { _hs_type_conversation };
static const int16 k_hs_parameters_236[] = { _hs_type_conversation };
static const int16 k_hs_parameters_237[] = { _hs_type_conversation };
static const int16 k_hs_parameters_238[] = { _hs_type_conversation };
static const int16 k_hs_parameters_239[] = { _hs_type_ai, _hs_type_ai };
static const int16 k_hs_parameters_240[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_241[] = { _hs_type_ai, _hs_type_enum_team };
static const int16 k_hs_parameters_242[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_243[] = { _hs_type_ai, _hs_type_boolean };
static const int16 k_hs_parameters_244[] = { _hs_type_enum_team, _hs_type_enum_team };
static const int16 k_hs_parameters_245[] = { _hs_type_boolean };
static const int16 k_hs_parameters_246[] = { _hs_type_cutscene_camera_point, _hs_type_short_integer };
static const int16 k_hs_parameters_247[] = { _hs_type_cutscene_camera_point, _hs_type_short_integer, _hs_type_object };
static const int16 k_hs_parameters_248[] = { _hs_type_animation_graph, _hs_type_string };
static const int16 k_hs_parameters_249[] = { _hs_type_unit };
static const int16 k_hs_parameters_250[] = { _hs_type_unit };
static const int16 k_hs_parameters_254[] = { _hs_type_real };
static const int16 k_hs_parameters_256[] = { _hs_type_string };
static const int16 k_hs_parameters_260[] = { _hs_type_string };
static const int16 k_hs_parameters_261[] = { _hs_type_string };
static const int16 k_hs_parameters_262[] = { _hs_type_enum_game_difficulty };
static const int16 k_hs_parameters_263[] = { _hs_type_string };
static const int16 k_hs_parameters_264[] = { _hs_type_short_integer };
static const int16 k_hs_parameters_272[] = { _hs_type_string };
static const int16 k_hs_parameters_275[] = { _hs_type_string };
static const int16 k_hs_parameters_276[] = { _hs_type_string };
static const int16 k_hs_parameters_277[] = { _hs_type_string };
static const int16 k_hs_parameters_278[] = { _hs_type_string };
static const int16 k_hs_parameters_279[] = { _hs_type_boolean };
static const int16 k_hs_parameters_283[] = { _hs_type_boolean };
static const int16 k_hs_parameters_284[] = { _hs_type_boolean };
static const int16 k_hs_parameters_285[] = { _hs_type_boolean };
static const int16 k_hs_parameters_288[] = { _hs_type_string, _hs_type_string };
static const int16 k_hs_parameters_289[] = { _hs_type_ai };
static const int16 k_hs_parameters_290[] = { _hs_type_string };
static const int16 k_hs_parameters_291[] = { _hs_type_string };
static const int16 k_hs_parameters_292[] = { _hs_type_real, _hs_type_real, _hs_type_real, _hs_type_short_integer };
static const int16 k_hs_parameters_293[] = { _hs_type_real, _hs_type_real, _hs_type_real, _hs_type_short_integer };
static const int16 k_hs_parameters_298[] = { _hs_type_boolean };
static const int16 k_hs_parameters_299[] = { _hs_type_cutscene_title };
static const int16 k_hs_parameters_300[] = { _hs_type_cutscene_title, _hs_type_real };
static const int16 k_hs_parameters_301[] = { _hs_type_boolean };
static const int16 k_hs_parameters_317[] = { _hs_type_string };
static const int16 k_hs_parameters_320[] = { _hs_type_string };
static const int16 k_hs_parameters_321[] = { _hs_type_string };
static const int16 k_hs_parameters_322[] = { _hs_type_short_integer };
static const int16 k_hs_parameters_323[] = { _hs_type_sound, _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_324[] = { _hs_type_sound };
static const int16 k_hs_parameters_325[] = { _hs_type_sound };
static const int16 k_hs_parameters_326[] = { _hs_type_looping_sound };
static const int16 k_hs_parameters_327[] = { _hs_type_looping_sound, _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_328[] = { _hs_type_looping_sound };
static const int16 k_hs_parameters_329[] = { _hs_type_looping_sound, _hs_type_real };
static const int16 k_hs_parameters_330[] = { _hs_type_looping_sound, _hs_type_boolean };
static const int16 k_hs_parameters_331[] = { _hs_type_string, _hs_type_boolean };
static const int16 k_hs_parameters_332[] = { _hs_type_string, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_333[] = { _hs_type_string, _hs_type_real };
static const int16 k_hs_parameters_334[] = { _hs_type_boolean };
static const int16 k_hs_parameters_335[] = { _hs_type_string, _hs_type_real, _hs_type_short_integer };
static const int16 k_hs_parameters_336[] = { _hs_type_vehicle, _hs_type_boolean };
static const int16 k_hs_parameters_338[] = { _hs_type_boolean };
static const int16 k_hs_parameters_339[] = { _hs_type_boolean };
static const int16 k_hs_parameters_354[] = { _hs_type_unit, _hs_type_starting_profile, _hs_type_boolean };
static const int16 k_hs_parameters_355[] = { _hs_type_short_integer, _hs_type_short_integer };
static const int16 k_hs_parameters_356[] = { _hs_type_boolean };
static const int16 k_hs_parameters_357[] = { _hs_type_boolean };
static const int16 k_hs_parameters_358[] = { _hs_type_boolean };
static const int16 k_hs_parameters_360[] = { _hs_type_navpoint, _hs_type_unit, _hs_type_cutscene_flag, _hs_type_real };
static const int16 k_hs_parameters_361[] = { _hs_type_navpoint, _hs_type_unit, _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_362[] = { _hs_type_navpoint, _hs_type_enum_team, _hs_type_cutscene_flag, _hs_type_real };
static const int16 k_hs_parameters_363[] = { _hs_type_navpoint, _hs_type_enum_team, _hs_type_object, _hs_type_real };
static const int16 k_hs_parameters_364[] = { _hs_type_unit, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_365[] = { _hs_type_unit, _hs_type_object };
static const int16 k_hs_parameters_366[] = { _hs_type_enum_team, _hs_type_cutscene_flag };
static const int16 k_hs_parameters_367[] = { _hs_type_enum_team, _hs_type_object };
static const int16 k_hs_parameters_369[] = { _hs_type_boolean };
static const int16 k_hs_parameters_371[] = { _hs_type_real, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_372[] = { _hs_type_real, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_373[] = { _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_374[] = { _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_375[] = { _hs_type_real };
static const int16 k_hs_parameters_376[] = { _hs_type_boolean };
static const int16 k_hs_parameters_377[] = { _hs_type_boolean };
static const int16 k_hs_parameters_378[] = { _hs_type_boolean };
static const int16 k_hs_parameters_379[] = { _hs_type_boolean };
static const int16 k_hs_parameters_380[] = { _hs_type_boolean };
static const int16 k_hs_parameters_381[] = { _hs_type_boolean };
static const int16 k_hs_parameters_382[] = { _hs_type_boolean };
static const int16 k_hs_parameters_384[] = { _hs_type_hud_message };
static const int16 k_hs_parameters_385[] = { _hs_type_hud_message };
static const int16 k_hs_parameters_386[] = { _hs_type_short_integer, _hs_type_short_integer };
static const int16 k_hs_parameters_387[] = { _hs_type_short_integer, _hs_type_short_integer };
static const int16 k_hs_parameters_388[] = { _hs_type_short_integer, _hs_type_short_integer, _hs_type_enum_hud_corner };
static const int16 k_hs_parameters_389[] = { _hs_type_boolean };
static const int16 k_hs_parameters_390[] = { _hs_type_boolean };
static const int16 k_hs_parameters_392[] = { _hs_type_boolean };
static const int16 k_hs_parameters_393[] = { _hs_type_boolean };
static const int16 k_hs_parameters_397[] = { _hs_type_real, _hs_type_real, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_399[] = { _hs_type_short_integer, _hs_type_real };
static const int16 k_hs_parameters_400[] = { _hs_type_boolean };
static const int16 k_hs_parameters_401[] = { _hs_type_short_integer, _hs_type_short_integer, _hs_type_real, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_402[] = { _hs_type_real, _hs_type_real, _hs_type_real, _hs_type_real, _hs_type_boolean, _hs_type_real };
static const int16 k_hs_parameters_403[] = { _hs_type_real, _hs_type_real, _hs_type_real };
static const int16 k_hs_parameters_404[] = { _hs_type_short_integer, _hs_type_real };
static const int16 k_hs_parameters_406[] = { _hs_type_real };
static const int16 k_hs_parameters_411[] = { _hs_type_boolean };
static const int16 k_hs_parameters_414[] = { _hs_type_boolean };
static const int16 k_hs_parameters_415[] = { _hs_type_short_integer };
static const int16 k_hs_parameters_417[] = { _hs_type_string };

static s_hs_function_definition g_hs_functions[] =
{
	{ _hs_passthrough, "begin", hs_evaluate_begin, 0, NULL, NULL },
	{ _hs_passthrough, "begin_random", hs_evaluate_begin_random, 0, NULL, NULL },
	{ _hs_passthrough, "if", hs_evaluate_if, 0, NULL, NULL },
	{ _hs_passthrough, "cond", NULL, 0, NULL, NULL },
	{ _hs_passthrough, "set", hs_evaluate_set, 0, NULL, NULL },
	{ _hs_type_boolean, "and", hs_evaluate_logical, 0, NULL, NULL },
	{ _hs_type_boolean, "or", hs_evaluate_logical, 0, NULL, NULL },
	{ _hs_type_real, "+", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_real, "-", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_real, "*", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_real, "/", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_real, "min", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_real, "max", hs_evaluate_arithmetic, 0, NULL, NULL },
	{ _hs_type_boolean, "=", hs_evaluate_equality, 0, NULL, NULL },
	{ _hs_type_boolean, "!=", hs_evaluate_equality, 0, NULL, NULL },
	{ _hs_type_boolean, ">", hs_evaluate_inequality, 0, NULL, NULL },
	{ _hs_type_boolean, "<", hs_evaluate_inequality, 0, NULL, NULL },
	{ _hs_type_boolean, ">=", hs_evaluate_inequality, 0, NULL, NULL },
	{ _hs_type_boolean, "<=", hs_evaluate_inequality, 0, NULL, NULL },
	{ _hs_type_void, "sleep", hs_evaluate_sleep, 0, NULL, NULL },
	{ _hs_type_void, "sleep_until", hs_evaluate_sleep_until, 0, NULL, NULL },
	{ _hs_type_void, "wake", hs_evaluate_wake, 0, NULL, NULL },
	{ _hs_type_void, "inspect", hs_evaluate_inspect, 0, NULL, NULL },
	{ _hs_type_unit, "unit", hs_evaluate_object_cast_up, 0, NULL, NULL },
	{ _hs_type_void, "ai_debug_communication_suppress", hs_evaluate_debug_string, 0, NULL, NULL },
	{ _hs_type_void, "ai_debug_communication_ignore", hs_evaluate_debug_string, 0, NULL, NULL },
	{ _hs_type_void, "ai_debug_communication_focus", hs_evaluate_debug_string, 0, NULL, NULL },
	{ _hs_type_boolean, "not", hs_evaluate_generic, 1, k_hs_parameters_27, NULL },
	{ _hs_type_void, "print", hs_evaluate_generic, 1, k_hs_parameters_28, NULL },
	{ _hs_type_object_list, "players", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "volume_teleport_players_not_inside", hs_evaluate_generic, 2, k_hs_parameters_30, NULL },
	{ _hs_type_boolean, "volume_test_object", hs_evaluate_generic, 2, k_hs_parameters_31, NULL },
	{ _hs_type_boolean, "volume_test_objects", hs_evaluate_generic, 2, k_hs_parameters_32, NULL },
	{ _hs_type_boolean, "volume_test_objects_all", hs_evaluate_generic, 2, k_hs_parameters_33, NULL },
	{ _hs_type_void, "object_teleport", hs_evaluate_generic, 2, k_hs_parameters_34, NULL },
	{ _hs_type_void, "object_set_facing", hs_evaluate_generic, 2, k_hs_parameters_35, NULL },
	{ _hs_type_void, "object_set_shield", hs_evaluate_generic, 2, k_hs_parameters_36, NULL },
	{ _hs_type_void, "object_set_permutation", hs_evaluate_generic, 3, k_hs_parameters_37, NULL },
	{ _hs_type_void, "object_create", hs_evaluate_generic, 1, k_hs_parameters_38, NULL },
	{ _hs_type_void, "object_destroy", hs_evaluate_generic, 1, k_hs_parameters_39, NULL },
	{ _hs_type_void, "object_create_anew", hs_evaluate_generic, 1, k_hs_parameters_40, NULL },
	{ _hs_type_void, "object_create_containing", hs_evaluate_generic, 1, k_hs_parameters_41, NULL },
	{ _hs_type_void, "object_create_anew_containing", hs_evaluate_generic, 1, k_hs_parameters_42, NULL },
	{ _hs_type_void, "object_destroy_containing", hs_evaluate_generic, 1, k_hs_parameters_43, NULL },
	{ _hs_type_void, "object_destroy_all", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_object, "list_get", hs_evaluate_generic, 2, k_hs_parameters_45, NULL },
	{ _hs_type_short_integer, "list_count", hs_evaluate_generic, 1, k_hs_parameters_46, NULL },
	{ _hs_type_void, "effect_new", hs_evaluate_generic, 2, k_hs_parameters_47, NULL },
	{ _hs_type_void, "effect_new_on_object_marker", hs_evaluate_generic, 3, k_hs_parameters_48, NULL },
	{ _hs_type_void, "damage_new", hs_evaluate_generic, 2, k_hs_parameters_49, NULL },
	{ _hs_type_void, "damage_object", hs_evaluate_generic, 2, k_hs_parameters_50, NULL },
	{ _hs_type_boolean, "objects_can_see_object", hs_evaluate_generic, 3, k_hs_parameters_51, NULL },
	{ _hs_type_boolean, "objects_can_see_flag", hs_evaluate_generic, 3, k_hs_parameters_52, NULL },
	{ _hs_type_void, "objects_delete_by_definition", hs_evaluate_generic, 1, k_hs_parameters_53, NULL },
	{ _hs_type_void, "sound_set_gain", hs_evaluate_generic, 2, k_hs_parameters_54, NULL },
	{ _hs_type_real, "sound_get_gain", hs_evaluate_generic, 1, k_hs_parameters_55, NULL },
	{ _hs_type_void, "script_recompile", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "script_doc", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "help", hs_evaluate_generic, 1, k_hs_parameters_58, NULL },
	{ _hs_type_short_integer, "random_range", hs_evaluate_generic, 2, k_hs_parameters_59, NULL },
	{ _hs_type_real, "real_random_range", hs_evaluate_generic, 2, k_hs_parameters_60, NULL },
	{ _hs_type_void, "numeric_countdown_timer_set", hs_evaluate_generic, 2, k_hs_parameters_61, NULL },
	{ _hs_type_short_integer, "numeric_countdown_timer_get", hs_evaluate_generic, 1, k_hs_parameters_62, NULL },
	{ _hs_type_void, "numeric_countdown_timer_stop", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "numeric_countdown_timer_restart", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "breakable_surfaces_enable", hs_evaluate_generic, 1, k_hs_parameters_65, NULL },
	{ _hs_type_boolean, "recording_play", hs_evaluate_generic, 2, k_hs_parameters_66, NULL },
	{ _hs_type_boolean, "recording_play_and_delete", hs_evaluate_generic, 2, k_hs_parameters_67, NULL },
	{ _hs_type_boolean, "recording_play_and_hover", hs_evaluate_generic, 2, k_hs_parameters_68, NULL },
	{ _hs_type_void, "recording_kill", hs_evaluate_generic, 1, k_hs_parameters_69, NULL },
	{ _hs_type_short_integer, "recording_time", hs_evaluate_generic, 1, k_hs_parameters_70, NULL },
	{ _hs_type_void, "object_set_ranged_attack_inhibited", hs_evaluate_generic, 2, k_hs_parameters_71, NULL },
	{ _hs_type_void, "object_set_melee_attack_inhibited", hs_evaluate_generic, 2, k_hs_parameters_72, NULL },
	{ _hs_type_void, "objects_dump_memory", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "object_set_collideable", hs_evaluate_generic, 2, k_hs_parameters_74, NULL },
	{ _hs_type_void, "object_set_scale", hs_evaluate_generic, 3, k_hs_parameters_75, NULL },
	{ _hs_type_void, "objects_attach", hs_evaluate_generic, 4, k_hs_parameters_76, NULL },
	{ _hs_type_void, "objects_detach", hs_evaluate_generic, 2, k_hs_parameters_77, NULL },
	{ _hs_type_void, "garbage_collect_now", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "object_cannot_take_damage", hs_evaluate_generic, 1, k_hs_parameters_79, NULL },
	{ _hs_type_void, "object_can_take_damage", hs_evaluate_generic, 1, k_hs_parameters_80, NULL },
	{ _hs_type_void, "object_beautify", hs_evaluate_generic, 2, k_hs_parameters_81, NULL },
	{ _hs_type_void, "objects_predict", hs_evaluate_generic, 1, k_hs_parameters_82, NULL },
	{ _hs_type_void, "object_type_predict", hs_evaluate_generic, 1, k_hs_parameters_83, NULL },
	{ _hs_type_void, "object_pvs_activate", hs_evaluate_generic, 1, k_hs_parameters_84, NULL },
	{ _hs_type_void, "object_pvs_set_object", hs_evaluate_generic, 1, k_hs_parameters_85, NULL },
	{ _hs_type_void, "object_pvs_set_camera", hs_evaluate_generic, 1, k_hs_parameters_86, NULL },
	{ _hs_type_void, "object_pvs_clear", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "render_lights", hs_evaluate_generic, 1, k_hs_parameters_88, NULL },
	{ _hs_type_short_integer, "scenery_get_animation_time", hs_evaluate_generic, 1, k_hs_parameters_89, NULL },
	{ _hs_type_void, "scenery_animation_start", hs_evaluate_generic, 3, k_hs_parameters_90, NULL },
	{ _hs_type_void, "scenery_animation_start_at_frame", hs_evaluate_generic, 4, k_hs_parameters_91, NULL },
	{ _hs_type_void, "render_effects", hs_evaluate_generic, 1, k_hs_parameters_92, NULL },
	{ _hs_type_void, "unit_can_blink", hs_evaluate_generic, 2, k_hs_parameters_93, NULL },
	{ _hs_type_void, "unit_open", hs_evaluate_generic, 1, k_hs_parameters_94, NULL },
	{ _hs_type_void, "unit_close", hs_evaluate_generic, 1, k_hs_parameters_95, NULL },
	{ _hs_type_void, "unit_kill", hs_evaluate_generic, 1, k_hs_parameters_96, NULL },
	{ _hs_type_void, "unit_kill_silent", hs_evaluate_generic, 1, k_hs_parameters_97, NULL },
	{ _hs_type_short_integer, "unit_get_custom_animation_time", hs_evaluate_generic, 1, k_hs_parameters_98, NULL },
	{ _hs_type_void, "unit_stop_custom_animation", hs_evaluate_generic, 1, k_hs_parameters_99, NULL },
	{ _hs_type_boolean, "unit_custom_animation_at_frame", hs_evaluate_generic, 5, k_hs_parameters_100, NULL },
	{ _hs_type_boolean, "custom_animation", hs_evaluate_generic, 4, k_hs_parameters_101, NULL },
	{ _hs_type_boolean, "custom_animation_list", hs_evaluate_generic, 4, k_hs_parameters_102, NULL },
	{ _hs_type_boolean, "unit_is_playing_custom_animation", hs_evaluate_generic, 1, k_hs_parameters_103, NULL },
	{ _hs_type_void, "unit_aim_without_turning", hs_evaluate_generic, 2, k_hs_parameters_104, NULL },
	{ _hs_type_void, "unit_set_emotion", hs_evaluate_generic, 2, k_hs_parameters_105, NULL },
	{ _hs_type_void, "unit_set_enterable_by_player", hs_evaluate_generic, 2, k_hs_parameters_106, NULL },
	{ _hs_type_void, "unit_enter_vehicle", hs_evaluate_generic, 3, k_hs_parameters_107, NULL },
	{ _hs_type_boolean, "vehicle_test_seat_list", hs_evaluate_generic, 3, k_hs_parameters_108, NULL },
	{ _hs_type_boolean, "vehicle_test_seat", hs_evaluate_generic, 3, k_hs_parameters_109, NULL },
	{ _hs_type_void, "unit_set_emotion_animation", hs_evaluate_generic, 2, k_hs_parameters_110, NULL },
	{ _hs_type_void, "unit_exit_vehicle", hs_evaluate_generic, 1, k_hs_parameters_111, NULL },
	{ _hs_type_void, "unit_set_maximum_vitality", hs_evaluate_generic, 3, k_hs_parameters_112, NULL },
	{ _hs_type_void, "units_set_maximum_vitality", hs_evaluate_generic, 3, k_hs_parameters_113, NULL },
	{ _hs_type_void, "unit_set_current_vitality", hs_evaluate_generic, 3, k_hs_parameters_114, NULL },
	{ _hs_type_void, "units_set_current_vitality", hs_evaluate_generic, 3, k_hs_parameters_115, NULL },
	{ _hs_type_short_integer, "vehicle_load_magic", hs_evaluate_generic, 3, k_hs_parameters_116, NULL },
	{ _hs_type_short_integer, "vehicle_unload", hs_evaluate_generic, 2, k_hs_parameters_117, NULL },
	{ _hs_type_void, "magic_seat_name", hs_evaluate_generic, 1, k_hs_parameters_118, NULL },
	{ _hs_type_void, "unit_set_seat", hs_evaluate_generic, 2, k_hs_parameters_119, NULL },
	{ _hs_type_void, "magic_melee_attack", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_object_list, "vehicle_riders", hs_evaluate_generic, 1, k_hs_parameters_121, NULL },
	{ _hs_type_unit, "vehicle_driver", hs_evaluate_generic, 1, k_hs_parameters_122, NULL },
	{ _hs_type_unit, "vehicle_gunner", hs_evaluate_generic, 1, k_hs_parameters_123, NULL },
	{ _hs_type_real, "unit_get_health", hs_evaluate_generic, 1, k_hs_parameters_124, NULL },
	{ _hs_type_real, "unit_get_shield", hs_evaluate_generic, 1, k_hs_parameters_125, NULL },
	{ _hs_type_short_integer, "unit_get_total_grenade_count", hs_evaluate_generic, 1, k_hs_parameters_126, NULL },
	{ _hs_type_boolean, "unit_has_weapon", hs_evaluate_generic, 2, k_hs_parameters_127, NULL },
	{ _hs_type_boolean, "unit_has_weapon_readied", hs_evaluate_generic, 2, k_hs_parameters_128, NULL },
	{ _hs_type_void, "unit_doesnt_drop_items", hs_evaluate_generic, 1, k_hs_parameters_129, NULL },
	{ _hs_type_void, "unit_impervious", hs_evaluate_generic, 2, k_hs_parameters_130, NULL },
	{ _hs_type_void, "unit_suspended", hs_evaluate_generic, 2, k_hs_parameters_131, NULL },
	{ _hs_type_boolean, "unit_solo_player_integrated_night_vision_is_active", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "units_set_desired_flashlight_state", hs_evaluate_generic, 2, k_hs_parameters_133, NULL },
	{ _hs_type_void, "unit_set_desired_flashlight_state", hs_evaluate_generic, 2, k_hs_parameters_134, NULL },
	{ _hs_type_boolean, "unit_get_current_flashlight_state", hs_evaluate_generic, 1, k_hs_parameters_135, NULL },
	{ _hs_type_void, "device_set_never_appears_locked", hs_evaluate_generic, 2, k_hs_parameters_136, NULL },
	{ _hs_type_real, "device_get_power", hs_evaluate_generic, 1, k_hs_parameters_137, NULL },
	{ _hs_type_void, "device_set_power", hs_evaluate_generic, 2, k_hs_parameters_138, NULL },
	{ _hs_type_boolean, "device_set_position", hs_evaluate_generic, 2, k_hs_parameters_139, NULL },
	{ _hs_type_real, "device_get_position", hs_evaluate_generic, 1, k_hs_parameters_140, NULL },
	{ _hs_type_void, "device_set_position_immediate", hs_evaluate_generic, 2, k_hs_parameters_141, NULL },
	{ _hs_type_real, "device_group_get", hs_evaluate_generic, 1, k_hs_parameters_142, NULL },
	{ _hs_type_boolean, "device_group_set", hs_evaluate_generic, 2, k_hs_parameters_143, NULL },
	{ _hs_type_void, "device_group_set_immediate", hs_evaluate_generic, 2, k_hs_parameters_144, NULL },
	{ _hs_type_void, "device_one_sided_set", hs_evaluate_generic, 2, k_hs_parameters_145, NULL },
	{ _hs_type_void, "device_operates_automatically_set", hs_evaluate_generic, 2, k_hs_parameters_146, NULL },
	{ _hs_type_void, "device_group_change_only_once_more_set", hs_evaluate_generic, 2, k_hs_parameters_147, NULL },
	{ _hs_type_void, "breakable_surfaces_reset", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_all_powerups", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_all_weapons", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_all_vehicles", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_teleport_to_camera", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_active_camouflage", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cheat_active_camouflage_local_player", hs_evaluate_generic, 1, k_hs_parameters_154, NULL },
	{ _hs_type_void, "cheats_load", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_free", hs_evaluate_generic, 1, k_hs_parameters_156, NULL },
	{ _hs_type_void, "ai_free_units", hs_evaluate_generic, 1, k_hs_parameters_157, NULL },
	{ _hs_type_void, "ai_attach", hs_evaluate_generic, 2, k_hs_parameters_158, NULL },
	{ _hs_type_void, "ai_attach_free", hs_evaluate_generic, 2, k_hs_parameters_159, NULL },
	{ _hs_type_void, "ai_detach", hs_evaluate_generic, 1, k_hs_parameters_160, NULL },
	{ _hs_type_void, "ai_place", hs_evaluate_generic, 1, k_hs_parameters_161, NULL },
	{ _hs_type_void, "ai_kill", hs_evaluate_generic, 1, k_hs_parameters_162, NULL },
	{ _hs_type_void, "ai_kill_silent", hs_evaluate_generic, 1, k_hs_parameters_163, NULL },
	{ _hs_type_void, "ai_erase", hs_evaluate_generic, 1, k_hs_parameters_164, NULL },
	{ _hs_type_void, "ai_erase_all", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_select", hs_evaluate_generic, 1, k_hs_parameters_166, NULL },
	{ _hs_type_void, "ai_deselect", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_spawn_actor", hs_evaluate_generic, 1, k_hs_parameters_168, NULL },
	{ _hs_type_void, "ai_set_respawn", hs_evaluate_generic, 2, k_hs_parameters_169, NULL },
	{ _hs_type_void, "ai_set_deaf", hs_evaluate_generic, 2, k_hs_parameters_170, NULL },
	{ _hs_type_void, "ai_set_blind", hs_evaluate_generic, 2, k_hs_parameters_171, NULL },
	{ _hs_type_void, "ai_magically_see_encounter", hs_evaluate_generic, 2, k_hs_parameters_172, NULL },
	{ _hs_type_void, "ai_magically_see_players", hs_evaluate_generic, 1, k_hs_parameters_173, NULL },
	{ _hs_type_void, "ai_magically_see_unit", hs_evaluate_generic, 2, k_hs_parameters_174, NULL },
	{ _hs_type_void, "ai_timer_start", hs_evaluate_generic, 1, k_hs_parameters_175, NULL },
	{ _hs_type_void, "ai_timer_expire", hs_evaluate_generic, 1, k_hs_parameters_176, NULL },
	{ _hs_type_void, "ai_attack", hs_evaluate_generic, 1, k_hs_parameters_177, NULL },
	{ _hs_type_void, "ai_defend", hs_evaluate_generic, 1, k_hs_parameters_178, NULL },
	{ _hs_type_void, "ai_retreat", hs_evaluate_generic, 1, k_hs_parameters_179, NULL },
	{ _hs_type_void, "ai_maneuver", hs_evaluate_generic, 1, k_hs_parameters_180, NULL },
	{ _hs_type_void, "ai_maneuver_enable", hs_evaluate_generic, 2, k_hs_parameters_181, NULL },
	{ _hs_type_void, "ai_migrate", hs_evaluate_generic, 2, k_hs_parameters_182, NULL },
	{ _hs_type_void, "ai_migrate_and_speak", hs_evaluate_generic, 3, k_hs_parameters_183, NULL },
	{ _hs_type_void, "ai_migrate_by_unit", hs_evaluate_generic, 2, k_hs_parameters_184, NULL },
	{ _hs_type_void, "ai_allegiance", hs_evaluate_generic, 2, k_hs_parameters_185, NULL },
	{ _hs_type_void, "ai_allegiance_remove", hs_evaluate_generic, 2, k_hs_parameters_186, NULL },
	{ _hs_type_short_integer, "ai_living_count", hs_evaluate_generic, 1, k_hs_parameters_187, NULL },
	{ _hs_type_real, "ai_living_fraction", hs_evaluate_generic, 1, k_hs_parameters_188, NULL },
	{ _hs_type_real, "ai_strength", hs_evaluate_generic, 1, k_hs_parameters_189, NULL },
	{ _hs_type_short_integer, "ai_swarm_count", hs_evaluate_generic, 1, k_hs_parameters_190, NULL },
	{ _hs_type_short_integer, "ai_nonswarm_count", hs_evaluate_generic, 1, k_hs_parameters_191, NULL },
	{ _hs_type_object_list, "ai_actors", hs_evaluate_generic, 1, k_hs_parameters_192, NULL },
	{ _hs_type_void, "ai_go_to_vehicle", hs_evaluate_generic, 3, k_hs_parameters_193, NULL },
	{ _hs_type_void, "ai_go_to_vehicle_override", hs_evaluate_generic, 3, k_hs_parameters_194, NULL },
	{ _hs_type_short_integer, "ai_going_to_vehicle", hs_evaluate_generic, 1, k_hs_parameters_195, NULL },
	{ _hs_type_void, "ai_exit_vehicle", hs_evaluate_generic, 1, k_hs_parameters_196, NULL },
	{ _hs_type_void, "ai_braindead", hs_evaluate_generic, 2, k_hs_parameters_197, NULL },
	{ _hs_type_void, "ai_braindead_by_unit", hs_evaluate_generic, 2, k_hs_parameters_198, NULL },
	{ _hs_type_void, "ai_disregard", hs_evaluate_generic, 2, k_hs_parameters_199, NULL },
	{ _hs_type_void, "ai_prefer_target", hs_evaluate_generic, 2, k_hs_parameters_200, NULL },
	{ _hs_type_void, "ai_teleport_to_starting_location", hs_evaluate_generic, 1, k_hs_parameters_201, NULL },
	{ _hs_type_void, "ai_teleport_to_starting_location_if_unsupported", hs_evaluate_generic, 1, k_hs_parameters_202, NULL },
	{ _hs_type_void, "ai_renew", hs_evaluate_generic, 1, k_hs_parameters_203, NULL },
	{ _hs_type_void, "ai_try_to_fight_nothing", hs_evaluate_generic, 1, k_hs_parameters_204, NULL },
	{ _hs_type_void, "ai_try_to_fight", hs_evaluate_generic, 2, k_hs_parameters_205, NULL },
	{ _hs_type_void, "ai_try_to_fight_player", hs_evaluate_generic, 1, k_hs_parameters_206, NULL },
	{ _hs_type_void, "ai_command_list", hs_evaluate_generic, 2, k_hs_parameters_207, NULL },
	{ _hs_type_void, "ai_command_list_by_unit", hs_evaluate_generic, 2, k_hs_parameters_208, NULL },
	{ _hs_type_void, "ai_command_list_advance", hs_evaluate_generic, 1, k_hs_parameters_209, NULL },
	{ _hs_type_void, "ai_command_list_advance_by_unit", hs_evaluate_generic, 1, k_hs_parameters_210, NULL },
	{ _hs_type_short_integer, "ai_command_list_status", hs_evaluate_generic, 1, k_hs_parameters_211, NULL },
	{ _hs_type_boolean, "ai_is_attacking", hs_evaluate_generic, 1, k_hs_parameters_212, NULL },
	{ _hs_type_void, "ai_force_active", hs_evaluate_generic, 2, k_hs_parameters_213, NULL },
	{ _hs_type_void, "ai_force_active_by_unit", hs_evaluate_generic, 2, k_hs_parameters_214, NULL },
	{ _hs_type_void, "ai_set_return_state", hs_evaluate_generic, 2, k_hs_parameters_215, NULL },
	{ _hs_type_void, "ai_set_current_state", hs_evaluate_generic, 2, k_hs_parameters_216, NULL },
	{ _hs_type_void, "ai_playfight", hs_evaluate_generic, 2, k_hs_parameters_217, NULL },
	{ _hs_type_short_integer, "ai_status", hs_evaluate_generic, 1, k_hs_parameters_218, NULL },
	{ _hs_type_void, "ai_reconnect", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_vehicle_encounter", hs_evaluate_generic, 2, k_hs_parameters_220, NULL },
	{ _hs_type_void, "ai_vehicle_enterable_distance", hs_evaluate_generic, 2, k_hs_parameters_221, NULL },
	{ _hs_type_void, "ai_vehicle_enterable_team", hs_evaluate_generic, 2, k_hs_parameters_222, NULL },
	{ _hs_type_void, "ai_vehicle_enterable_actor_type", hs_evaluate_generic, 2, k_hs_parameters_223, NULL },
	{ _hs_type_void, "ai_vehicle_enterable_actors", hs_evaluate_generic, 2, k_hs_parameters_224, NULL },
	{ _hs_type_void, "ai_vehicle_enterable_disable", hs_evaluate_generic, 1, k_hs_parameters_225, NULL },
	{ _hs_type_void, "ai_look_at_object", hs_evaluate_generic, 2, k_hs_parameters_226, NULL },
	{ _hs_type_void, "ai_stop_looking", hs_evaluate_generic, 1, k_hs_parameters_227, NULL },
	{ _hs_type_void, "ai_automatic_migration_target", hs_evaluate_generic, 2, k_hs_parameters_228, NULL },
	{ _hs_type_void, "ai_follow_target_disable", hs_evaluate_generic, 1, k_hs_parameters_229, NULL },
	{ _hs_type_void, "ai_follow_target_players", hs_evaluate_generic, 1, k_hs_parameters_230, NULL },
	{ _hs_type_void, "ai_follow_target_unit", hs_evaluate_generic, 2, k_hs_parameters_231, NULL },
	{ _hs_type_void, "ai_follow_target_ai", hs_evaluate_generic, 2, k_hs_parameters_232, NULL },
	{ _hs_type_void, "ai_follow_distance", hs_evaluate_generic, 2, k_hs_parameters_233, NULL },
	{ _hs_type_boolean, "ai_conversation", hs_evaluate_generic, 1, k_hs_parameters_234, NULL },
	{ _hs_type_void, "ai_conversation_stop", hs_evaluate_generic, 1, k_hs_parameters_235, NULL },
	{ _hs_type_void, "ai_conversation_advance", hs_evaluate_generic, 1, k_hs_parameters_236, NULL },
	{ _hs_type_short_integer, "ai_conversation_line", hs_evaluate_generic, 1, k_hs_parameters_237, NULL },
	{ _hs_type_short_integer, "ai_conversation_status", hs_evaluate_generic, 1, k_hs_parameters_238, NULL },
	{ _hs_type_void, "ai_link_activation", hs_evaluate_generic, 2, k_hs_parameters_239, NULL },
	{ _hs_type_void, "ai_berserk", hs_evaluate_generic, 2, k_hs_parameters_240, NULL },
	{ _hs_type_void, "ai_set_team", hs_evaluate_generic, 2, k_hs_parameters_241, NULL },
	{ _hs_type_void, "ai_allow_charge", hs_evaluate_generic, 2, k_hs_parameters_242, NULL },
	{ _hs_type_void, "ai_allow_dormant", hs_evaluate_generic, 2, k_hs_parameters_243, NULL },
	{ _hs_type_boolean, "ai_allegiance_broken", hs_evaluate_generic, 2, k_hs_parameters_244, NULL },
	{ _hs_type_void, "camera_control", hs_evaluate_generic, 1, k_hs_parameters_245, NULL },
	{ _hs_type_void, "camera_set", hs_evaluate_generic, 2, k_hs_parameters_246, NULL },
	{ _hs_type_void, "camera_set_relative", hs_evaluate_generic, 3, k_hs_parameters_247, NULL },
	{ _hs_type_void, "camera_set_animation", hs_evaluate_generic, 2, k_hs_parameters_248, NULL },
	{ _hs_type_void, "camera_set_first_person", hs_evaluate_generic, 1, k_hs_parameters_249, NULL },
	{ _hs_type_void, "camera_set_dead", hs_evaluate_generic, 1, k_hs_parameters_250, NULL },
	{ _hs_type_short_integer, "camera_time", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "debug_camera_load", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "debug_camera_save", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_speed", hs_evaluate_generic, 1, k_hs_parameters_254, NULL },
	{ _hs_type_long_integer, "game_time", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_variant", hs_evaluate_generic, 1, k_hs_parameters_256, NULL },
	{ _hs_type_enum_game_difficulty, "game_difficulty_get", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_enum_game_difficulty, "game_difficulty_get_real", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "map_reset", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "map_name", hs_evaluate_generic, 1, k_hs_parameters_260, NULL },
	{ _hs_type_void, "multiplayer_map_name", hs_evaluate_generic, 1, k_hs_parameters_261, NULL },
	{ _hs_type_void, "game_difficulty_set", hs_evaluate_generic, 1, k_hs_parameters_262, NULL },
	{ _hs_type_void, "crash", hs_evaluate_generic, 1, k_hs_parameters_263, NULL },
	{ _hs_type_void, "switch_bsp", hs_evaluate_generic, 1, k_hs_parameters_264, NULL },
	{ _hs_type_short_integer, "structure_bsp_index", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "version", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "playback", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "texture_cache_flush", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "sound_cache_flush", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "debug_memory", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "debug_memory_by_file", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "debug_memory_for_file", hs_evaluate_generic, 1, k_hs_parameters_272, NULL },
	{ _hs_type_void, "debug_tags", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "profile_reset", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "profile_dump", hs_evaluate_generic, 1, k_hs_parameters_275, NULL },
	{ _hs_type_void, "profile_activate", hs_evaluate_generic, 1, k_hs_parameters_276, NULL },
	{ _hs_type_void, "profile_deactivate", hs_evaluate_generic, 1, k_hs_parameters_277, NULL },
	{ _hs_type_void, "profile_graph_toggle", hs_evaluate_generic, 1, k_hs_parameters_278, NULL },
	{ _hs_type_void, "debug_pvs", hs_evaluate_generic, 1, k_hs_parameters_279, NULL },
	{ _hs_type_void, "radiosity_start", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "radiosity_save", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "radiosity_debug_point", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai", hs_evaluate_generic, 1, k_hs_parameters_283, NULL },
	{ _hs_type_void, "ai_dialogue_triggers", hs_evaluate_generic, 1, k_hs_parameters_284, NULL },
	{ _hs_type_void, "ai_grenades", hs_evaluate_generic, 1, k_hs_parameters_285, NULL },
	{ _hs_type_void, "ai_lines", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_debug_sound_point_set", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ai_debug_vocalize", hs_evaluate_generic, 2, k_hs_parameters_288, NULL },
	{ _hs_type_void, "ai_debug_teleport_to", hs_evaluate_generic, 1, k_hs_parameters_289, NULL },
	{ _hs_type_void, "ai_debug_speak", hs_evaluate_generic, 1, k_hs_parameters_290, NULL },
	{ _hs_type_void, "ai_debug_speak_list", hs_evaluate_generic, 1, k_hs_parameters_291, NULL },
	{ _hs_type_void, "fade_in", hs_evaluate_generic, 4, k_hs_parameters_292, NULL },
	{ _hs_type_void, "fade_out", hs_evaluate_generic, 4, k_hs_parameters_293, NULL },
	{ _hs_type_void, "cinematic_start", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cinematic_stop", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cinematic_skip_start_internal", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cinematic_skip_stop_internal", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cinematic_show_letterbox", hs_evaluate_generic, 1, k_hs_parameters_298, NULL },
	{ _hs_type_void, "cinematic_set_title", hs_evaluate_generic, 1, k_hs_parameters_299, NULL },
	{ _hs_type_void, "cinematic_set_title_delayed", hs_evaluate_generic, 2, k_hs_parameters_300, NULL },
	{ _hs_type_void, "cinematic_suppress_bsp_object_creation", hs_evaluate_generic, 1, k_hs_parameters_301, NULL },
	{ _hs_type_void, "attract_mode_start", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_won", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_lost", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_safe_to_save", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_all_quiet", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_safe_to_speak", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_is_cooperative", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_save", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_save_cancel", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_save_no_timeout", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_save_totally_unsafe", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_saving", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "game_revert", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "game_reverted", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "core_save", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "core_save_name", hs_evaluate_generic, 1, k_hs_parameters_317, NULL },
	{ _hs_type_void, "core_load", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "core_load_at_startup", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "core_load_name", hs_evaluate_generic, 1, k_hs_parameters_320, NULL },
	{ _hs_type_void, "core_load_name_at_startup", hs_evaluate_generic, 1, k_hs_parameters_321, NULL },
	{ _hs_type_void, "game_skip_ticks", hs_evaluate_generic, 1, k_hs_parameters_322, NULL },
	{ _hs_type_void, "sound_impulse_start", hs_evaluate_generic, 3, k_hs_parameters_323, NULL },
	{ _hs_type_long_integer, "sound_impulse_time", hs_evaluate_generic, 1, k_hs_parameters_324, NULL },
	{ _hs_type_void, "sound_impulse_stop", hs_evaluate_generic, 1, k_hs_parameters_325, NULL },
	{ _hs_type_void, "sound_looping_predict", hs_evaluate_generic, 1, k_hs_parameters_326, NULL },
	{ _hs_type_void, "sound_looping_start", hs_evaluate_generic, 3, k_hs_parameters_327, NULL },
	{ _hs_type_void, "sound_looping_stop", hs_evaluate_generic, 1, k_hs_parameters_328, NULL },
	{ _hs_type_void, "sound_looping_set_scale", hs_evaluate_generic, 2, k_hs_parameters_329, NULL },
	{ _hs_type_void, "sound_looping_set_alternate", hs_evaluate_generic, 2, k_hs_parameters_330, NULL },
	{ _hs_type_void, "debug_sounds_enable", hs_evaluate_generic, 2, k_hs_parameters_331, NULL },
	{ _hs_type_void, "debug_sounds_distances", hs_evaluate_generic, 3, k_hs_parameters_332, NULL },
	{ _hs_type_void, "debug_sounds_wet", hs_evaluate_generic, 2, k_hs_parameters_333, NULL },
	{ _hs_type_void, "sound_enable", hs_evaluate_generic, 1, k_hs_parameters_334, NULL },
	{ _hs_type_void, "sound_class_set_gain", hs_evaluate_generic, 3, k_hs_parameters_335, NULL },
	{ _hs_type_void, "vehicle_hover", hs_evaluate_generic, 2, k_hs_parameters_336, NULL },
	{ _hs_type_void, "players_unzoom_all", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "player_enable_input", hs_evaluate_generic, 1, k_hs_parameters_338, NULL },
	{ _hs_type_boolean, "player_camera_control", hs_evaluate_generic, 1, k_hs_parameters_339, NULL },
	{ _hs_type_void, "player_action_test_reset", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_jump", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_primary_trigger", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_grenade_trigger", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_zoom", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_action", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_accept", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_back", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_look_relative_up", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_look_relative_down", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_look_relative_left", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_look_relative_right", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_look_relative_all_directions", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player_action_test_move_relative_all_directions", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "player_add_equipment", hs_evaluate_generic, 3, k_hs_parameters_354, NULL },
	{ _hs_type_void, "debug_teleport_player", hs_evaluate_generic, 2, k_hs_parameters_355, NULL },
	{ _hs_type_boolean, "show_hud", hs_evaluate_generic, 1, k_hs_parameters_356, NULL },
	{ _hs_type_boolean, "show_hud_help_text", hs_evaluate_generic, 1, k_hs_parameters_357, NULL },
	{ _hs_type_void, "enable_hud_help_flash", hs_evaluate_generic, 1, k_hs_parameters_358, NULL },
	{ _hs_type_void, "hud_help_flash_restart", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "activate_nav_point_flag", hs_evaluate_generic, 4, k_hs_parameters_360, NULL },
	{ _hs_type_void, "activate_nav_point_object", hs_evaluate_generic, 4, k_hs_parameters_361, NULL },
	{ _hs_type_void, "activate_team_nav_point_flag", hs_evaluate_generic, 4, k_hs_parameters_362, NULL },
	{ _hs_type_void, "activate_team_nav_point_object", hs_evaluate_generic, 4, k_hs_parameters_363, NULL },
	{ _hs_type_void, "deactivate_nav_point_flag", hs_evaluate_generic, 2, k_hs_parameters_364, NULL },
	{ _hs_type_void, "deactivate_nav_point_object", hs_evaluate_generic, 2, k_hs_parameters_365, NULL },
	{ _hs_type_void, "deactivate_team_nav_point_flag", hs_evaluate_generic, 2, k_hs_parameters_366, NULL },
	{ _hs_type_void, "deactivate_team_nav_point_object", hs_evaluate_generic, 2, k_hs_parameters_367, NULL },
	{ _hs_type_void, "cls", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "error_overflow_suppression", hs_evaluate_generic, 1, k_hs_parameters_369, NULL },
	{ _hs_type_void, "structure_lens_flares_place", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "player_effect_set_max_translation", hs_evaluate_generic, 3, k_hs_parameters_371, NULL },
	{ _hs_type_void, "player_effect_set_max_rotation", hs_evaluate_generic, 3, k_hs_parameters_372, NULL },
	{ _hs_type_void, "player_effect_set_max_rumble", hs_evaluate_generic, 2, k_hs_parameters_373, NULL },
	{ _hs_type_void, "player_effect_start", hs_evaluate_generic, 2, k_hs_parameters_374, NULL },
	{ _hs_type_void, "player_effect_stop", hs_evaluate_generic, 1, k_hs_parameters_375, NULL },
	{ _hs_type_void, "hud_show_health", hs_evaluate_generic, 1, k_hs_parameters_376, NULL },
	{ _hs_type_void, "hud_blink_health", hs_evaluate_generic, 1, k_hs_parameters_377, NULL },
	{ _hs_type_void, "hud_show_shield", hs_evaluate_generic, 1, k_hs_parameters_378, NULL },
	{ _hs_type_void, "hud_blink_shield", hs_evaluate_generic, 1, k_hs_parameters_379, NULL },
	{ _hs_type_void, "hud_show_motion_sensor", hs_evaluate_generic, 1, k_hs_parameters_380, NULL },
	{ _hs_type_void, "hud_blink_motion_sensor", hs_evaluate_generic, 1, k_hs_parameters_381, NULL },
	{ _hs_type_void, "hud_show_crosshair", hs_evaluate_generic, 1, k_hs_parameters_382, NULL },
	{ _hs_type_void, "hud_clear_messages", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "hud_set_help_text", hs_evaluate_generic, 1, k_hs_parameters_384, NULL },
	{ _hs_type_void, "hud_set_objective_text", hs_evaluate_generic, 1, k_hs_parameters_385, NULL },
	{ _hs_type_void, "hud_set_timer_time", hs_evaluate_generic, 2, k_hs_parameters_386, NULL },
	{ _hs_type_void, "hud_set_timer_warning_time", hs_evaluate_generic, 2, k_hs_parameters_387, NULL },
	{ _hs_type_void, "hud_set_timer_position", hs_evaluate_generic, 3, k_hs_parameters_388, NULL },
	{ _hs_type_void, "show_hud_timer", hs_evaluate_generic, 1, k_hs_parameters_389, NULL },
	{ _hs_type_void, "pause_hud_timer", hs_evaluate_generic, 1, k_hs_parameters_390, NULL },
	{ _hs_type_short_integer, "hud_get_timer_ticks", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "time_code_show", hs_evaluate_generic, 1, k_hs_parameters_392, NULL },
	{ _hs_type_void, "time_code_start", hs_evaluate_generic, 1, k_hs_parameters_393, NULL },
	{ _hs_type_void, "time_code_reset", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "rasterizer_decals_flush", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "rasterizer_fps_accumulate", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "rasterizer_model_ambient_reflection_tint", hs_evaluate_generic, 4, k_hs_parameters_397, NULL },
	{ _hs_type_void, "rasterizer_lights_reset_for_new_map", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "script_screen_effect_set_value", hs_evaluate_generic, 2, k_hs_parameters_399, NULL },
	{ _hs_type_void, "cinematic_screen_effect_start", hs_evaluate_generic, 1, k_hs_parameters_400, NULL },
	{ _hs_type_void, "cinematic_screen_effect_set_convolution", hs_evaluate_generic, 5, k_hs_parameters_401, NULL },
	{ _hs_type_void, "cinematic_screen_effect_set_filter", hs_evaluate_generic, 6, k_hs_parameters_402, NULL },
	{ _hs_type_void, "cinematic_screen_effect_set_filter_desaturation_tint", hs_evaluate_generic, 3, k_hs_parameters_403, NULL },
	{ _hs_type_void, "cinematic_screen_effect_set_video", hs_evaluate_generic, 2, k_hs_parameters_404, NULL },
	{ _hs_type_void, "cinematic_screen_effect_stop", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "cinematic_set_near_clip_distance", hs_evaluate_generic, 1, k_hs_parameters_406, NULL },
	{ _hs_type_void, "enumerate_memory_units", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "delete_save_game_files", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "fast_setup_network_server", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "profile_unlock_solo_levels", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "player0_look_invert_pitch", hs_evaluate_generic, 1, k_hs_parameters_411, NULL },
	{ _hs_type_boolean, "player0_look_pitch_is_inverted", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_boolean, "player0_joystick_set_is_normal", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "ui_widget_show_path", hs_evaluate_generic, 1, k_hs_parameters_414, NULL },
	{ _hs_type_void, "display_scenario_help", hs_evaluate_generic, 1, k_hs_parameters_415, NULL },
	{ _hs_type_void, "network_game_start_now", hs_evaluate_generic, 0, NULL, NULL },
	{ _hs_type_void, "xbox_set_machine_name", hs_evaluate_generic, 1, k_hs_parameters_417, NULL },
};

static const s_hs_external_global_definition k_hs_external_globals[] =
{
	{ "rasterizer_near_clip_distance", _hs_type_real },
	{ "rasterizer_far_clip_distance", _hs_type_real },
	{ "rasterizer_first_person_weapon_near_clip_distance", _hs_type_real },
	{ "rasterizer_first_person_weapon_far_clip_distance", _hs_type_real },
	{ "rasterizer_pushbuffer_size", _hs_type_short_integer },
	{ "rasterizer_pushbuffer_kickoff_size", _hs_type_short_integer },
	{ "rasterizer_floating_point_zbuffer", _hs_type_boolean },
	{ "rasterizer_framerate_throttle", _hs_type_boolean },
	{ "rasterizer_framerate_stabilization", _hs_type_boolean },
	{ "rasterizer_refresh_rate", _hs_type_short_integer },
	{ "rasterizer_frame_bounds_left", _hs_type_short_integer },
	{ "rasterizer_frame_bounds_right", _hs_type_short_integer },
	{ "rasterizer_frame_bounds_top", _hs_type_short_integer },
	{ "rasterizer_frame_bounds_bottom", _hs_type_short_integer },
	{ "rasterizer_stats", _hs_type_short_integer },
	{ "rasterizer_mode", _hs_type_short_integer },
	{ "rasterizer_wireframe", _hs_type_boolean },
	{ "rasterizer_smart", _hs_type_boolean },
	{ "rasterizer_debug_model_vertices", _hs_type_boolean },
	{ "rasterizer_debug_model_lod", _hs_type_short_integer },
	{ "rasterizer_debug_transparents", _hs_type_boolean },
	{ "rasterizer_debug_meter_shader", _hs_type_boolean },
	{ "rasterizer_models", _hs_type_boolean },
	{ "rasterizer_model_transparents", _hs_type_boolean },
	{ "rasterizer_draw_first_person_weapon_first", _hs_type_boolean },
	{ "rasterizer_stencil_mask", _hs_type_boolean },
	{ "rasterizer_environment", _hs_type_boolean },
	{ "rasterizer_environment_lightmaps", _hs_type_boolean },
	{ "rasterizer_environment_shadows", _hs_type_boolean },
	{ "rasterizer_environment_diffuse_lights", _hs_type_boolean },
	{ "rasterizer_environment_diffuse_textures", _hs_type_boolean },
	{ "rasterizer_environment_decals", _hs_type_boolean },
	{ "rasterizer_environment_specular_lights", _hs_type_boolean },
	{ "rasterizer_environment_specular_lightmaps", _hs_type_boolean },
	{ "rasterizer_environment_reflection_lightmap_mask", _hs_type_boolean },
	{ "rasterizer_environment_reflection_mirrors", _hs_type_boolean },
	{ "rasterizer_environment_reflections", _hs_type_boolean },
	{ "rasterizer_environment_transparents", _hs_type_boolean },
	{ "rasterizer_environment_fog", _hs_type_boolean },
	{ "rasterizer_environment_fog_screen", _hs_type_boolean },
	{ "rasterizer_water", _hs_type_boolean },
	{ "rasterizer_lens_flares", _hs_type_boolean },
	{ "rasterizer_dynamic_unlit_geometry", _hs_type_boolean },
	{ "rasterizer_dynamic_lit_geometry", _hs_type_boolean },
	{ "rasterizer_dynamic_screen_geometry", _hs_type_boolean },
	{ "rasterizer_hud_motion_sensor", _hs_type_boolean },
	{ "rasterizer_detail_objects", _hs_type_boolean },
	{ "rasterizer_debug_geometry", _hs_type_boolean },
	{ "rasterizer_debug_geometry_multipass", _hs_type_boolean },
	{ "rasterizer_fog_atmosphere", _hs_type_boolean },
	{ "rasterizer_fog_plane", _hs_type_boolean },
	{ "rasterizer_bump_mapping", _hs_type_boolean },
	{ "rasterizer_lightmap_ambient", _hs_type_real },
	{ "rasterizer_lightmap_mode", _hs_type_short_integer },
	{ "rasterizer_lightmaps_incident_radiosity", _hs_type_boolean },
	{ "rasterizer_lightmaps_filtering", _hs_type_boolean },
	{ "rasterizer_model_lighting_ambient", _hs_type_real },
	{ "rasterizer_environment_alpha_testing", _hs_type_boolean },
	{ "rasterizer_environment_specular_mask", _hs_type_boolean },
	{ "rasterizer_shadows_convolution", _hs_type_boolean },
	{ "rasterizer_shadows_debug", _hs_type_boolean },
	{ "rasterizer_water_mipmapping", _hs_type_boolean },
	{ "rasterizer_active_camouflage", _hs_type_boolean },
	{ "rasterizer_active_camouflage_multipass", _hs_type_boolean },
	{ "rasterizer_plasma_energy", _hs_type_boolean },
	{ "rasterizer_lens_flares_occlusion", _hs_type_boolean },
	{ "rasterizer_lens_flares_occlusion_debug", _hs_type_boolean },
	{ "rasterizer_ray_of_buddha", _hs_type_boolean },
	{ "rasterizer_screen_flashes", _hs_type_boolean },
	{ "rasterizer_screen_effects", _hs_type_boolean },
	{ "rasterizer_DXTC_noise", _hs_type_boolean },
	{ "rasterizer_soft_filter", _hs_type_boolean },
	{ "rasterizer_secondary_render_target_debug", _hs_type_boolean },
	{ "rasterizer_profile_log", _hs_type_boolean },
	{ "rasterizer_detail_objects_offset_multiplier", _hs_type_real },
	{ "rasterizer_zbias", _hs_type_long_integer },
	{ "rasterizer_zoffset", _hs_type_real },
	{ "force_all_player_views_to_default_player", _hs_type_boolean },
	{ "rasterizer_safe_frame_bounds", _hs_type_boolean },
	{ "freeze_flying_camera", _hs_type_short_integer },
	{ "rasterizer_zsprites", _hs_type_boolean },
	{ "rasterizer_filthy_decal_fog_hack", _hs_type_boolean },
	{ "rasterizer_splitscreen_VB_optimization", _hs_type_boolean },
	{ "rasterizer_profile_print_locks", _hs_type_boolean },
	{ "rasterizer_profile_objectlock_time", _hs_type_real },
	{ "pad3", _hs_type_short_integer },
	{ "pad3_scale", _hs_type_real },
	{ "f0", _hs_type_real },
	{ "f1", _hs_type_real },
	{ "f2", _hs_type_real },
	{ "f3", _hs_type_real },
	{ "f4", _hs_type_real },
	{ "f5", _hs_type_real },
	{ "rasterizer_transparent_pixel_counter", _hs_type_boolean },
	{ "debug_no_frustum_clip", _hs_type_boolean },
	{ "debug_frustum", _hs_type_boolean },
	{ "debug_bink", _hs_type_boolean },
	{ "screenshot_size", _hs_type_short_integer },
	{ "screenshot_count", _hs_type_short_integer },
	{ "terminal_render", _hs_type_boolean },
	{ "console_dump_to_file", _hs_type_boolean },
	{ "player_spawn_count", _hs_type_short_integer },
	{ "debug_object_garbage_collection", _hs_type_boolean },
	{ "debug_render_freeze", _hs_type_boolean },
	{ "debug_no_drawing", _hs_type_boolean },
	{ "debug_input_target", _hs_type_short_integer },
	{ "temporary_hud", _hs_type_boolean },
	{ "debug_leaf_index", _hs_type_long_integer },
	{ "debug_leaf_portal_index", _hs_type_long_integer },
	{ "debug_leaf_portals", _hs_type_boolean },
	{ "debug_unit_all_animations", _hs_type_boolean },
	{ "debug_unit_animations", _hs_type_boolean },
	{ "debug_unit_illumination", _hs_type_boolean },
	{ "debug_damage_taken", _hs_type_boolean },
	{ "cheat_deathless_player", _hs_type_boolean },
	{ "cheat_jetpack", _hs_type_boolean },
	{ "cheat_infinite_ammo", _hs_type_boolean },
	{ "cheat_bottomless_clip", _hs_type_boolean },
	{ "cheat_bump_possession", _hs_type_boolean },
	{ "cheat_super_jump", _hs_type_boolean },
	{ "cheat_reflexive_damage_effects", _hs_type_boolean },
	{ "cheat_medusa", _hs_type_boolean },
	{ "cheat_omnipotent", _hs_type_boolean },
	{ "cheat_controller", _hs_type_boolean },
	{ "effects_corpse_nonviolent", _hs_type_boolean },
	{ "debug_effects_nonviolent", _hs_type_boolean },
	{ "debug_sound_cache", _hs_type_boolean },
	{ "debug_sound", _hs_type_boolean },
	{ "debug_looping_sound", _hs_type_boolean },
	{ "debug_sound_channels", _hs_type_boolean },
	{ "loud_dialog_hack", _hs_type_boolean },
	{ "sound_gain_under_dialog", _hs_type_real },
	{ "debug_sound_environment", _hs_type_boolean },
	{ "object_light_ambient_base", _hs_type_real },
	{ "object_light_ambient_scale", _hs_type_real },
	{ "object_light_secondary_scale", _hs_type_real },
	{ "object_light_interpolate", _hs_type_boolean },
	{ "model_animation_compression", _hs_type_boolean },
	{ "model_animation_data_compressed_size", _hs_type_long_integer },
	{ "model_animation_data_uncompressed_size", _hs_type_long_integer },
	{ "model_animation_data_compression_savings_in_bytes", _hs_type_long_integer },
	{ "model_animation_data_compression_savings_in_bytes_at_import", _hs_type_long_integer },
	{ "model_animation_data_compression_savings_in_percent", _hs_type_real },
	{ "model_animation_bullshit0", _hs_type_long_integer },
	{ "model_animation_bullshit1", _hs_type_long_integer },
	{ "model_animation_bullshit2", _hs_type_long_integer },
	{ "model_animation_bullshit3", _hs_type_long_integer },
	{ "rider_ejection", _hs_type_boolean },
	{ "stun_enable", _hs_type_boolean },
	{ "debug_sprites", _hs_type_boolean },
	{ "debug_portals", _hs_type_boolean },
	{ "debug_inactive_objects", _hs_type_boolean },
	{ "render_contrails", _hs_type_boolean },
	{ "render_particles", _hs_type_boolean },
	{ "render_psystems", _hs_type_boolean },
	{ "render_wsystems", _hs_type_boolean },
	{ "debug_objects", _hs_type_boolean },
	{ "debug_objects_position_velocity", _hs_type_boolean },
	{ "debug_objects_root_node", _hs_type_boolean },
	{ "debug_objects_bounding_spheres", _hs_type_boolean },
	{ "debug_objects_collision_models", _hs_type_boolean },
	{ "debug_objects_physics", _hs_type_boolean },
	{ "debug_objects_names", _hs_type_boolean },
	{ "debug_objects_pathfinding_spheres", _hs_type_boolean },
	{ "debug_objects_unit_vectors", _hs_type_boolean },
	{ "debug_objects_unit_seats", _hs_type_boolean },
	{ "debug_objects_unit_mouth_apeture", _hs_type_boolean },
	{ "debug_objects_biped_physics_pills", _hs_type_boolean },
	{ "debug_objects_biped_autoaim_pills", _hs_type_boolean },
	{ "debug_objects_vehicle_powered_mass_points", _hs_type_boolean },
	{ "debug_objects_devices", _hs_type_boolean },
	{ "render_model_nodes", _hs_type_boolean },
	{ "render_model_vertex_counts", _hs_type_boolean },
	{ "render_model_index_counts", _hs_type_boolean },
	{ "render_model_markers", _hs_type_boolean },
	{ "render_model_no_geometry", _hs_type_boolean },
	{ "render_shadows", _hs_type_boolean },
	{ "debug_damage", _hs_type_boolean },
	{ "debug_scripting", _hs_type_boolean },
	{ "debug_trigger_volumes", _hs_type_boolean },
	{ "debug_point_physics", _hs_type_boolean },
	{ "debug_physics_disable_penetration_freeze", _hs_type_boolean },
	{ "debug_motion_sensor_draw_all_units", _hs_type_boolean },
	{ "collision_debug", _hs_type_boolean },
	{ "collision_debug_spray", _hs_type_boolean },
	{ "collision_debug_features", _hs_type_boolean },
	{ "collision_debug_repeat", _hs_type_boolean },
	{ "collision_debug_flag_front_facing_surfaces", _hs_type_boolean },
	{ "collision_debug_flag_back_facing_surfaces", _hs_type_boolean },
	{ "collision_debug_flag_ignore_two_sided_surfaces", _hs_type_boolean },
	{ "collision_debug_flag_ignore_invisible_surfaces", _hs_type_boolean },
	{ "collision_debug_flag_ignore_breakable_surfaces", _hs_type_boolean },
	{ "collision_debug_flag_structure", _hs_type_boolean },
	{ "collision_debug_flag_media", _hs_type_boolean },
	{ "collision_debug_flag_objects", _hs_type_boolean },
	{ "collision_debug_flag_objects_bipeds", _hs_type_boolean },
	{ "collision_debug_flag_objects_vehicles", _hs_type_boolean },
	{ "collision_debug_flag_objects_weapons", _hs_type_boolean },
	{ "collision_debug_flag_objects_equipment", _hs_type_boolean },
	{ "collision_debug_flag_objects_projectiles", _hs_type_boolean },
	{ "collision_debug_flag_objects_scenery", _hs_type_boolean },
	{ "collision_debug_flag_objects_machines", _hs_type_boolean },
	{ "collision_debug_flag_objects_controls", _hs_type_boolean },
	{ "collision_debug_flag_objects_light_fixtures", _hs_type_boolean },
	{ "collision_debug_flag_objects_placeholders", _hs_type_boolean },
	{ "collision_debug_flag_try_to_keep_location_valid", _hs_type_boolean },
	{ "collision_debug_flag_skip_passthrough_bipeds", _hs_type_boolean },
	{ "collision_debug_flag_use_vehicle_physics", _hs_type_boolean },
	{ "collision_debug_point_x", _hs_type_real },
	{ "collision_debug_point_y", _hs_type_real },
	{ "collision_debug_point_z", _hs_type_real },
	{ "collision_debug_vector_i", _hs_type_real },
	{ "collision_debug_vector_j", _hs_type_real },
	{ "collision_debug_vector_k", _hs_type_real },
	{ "collision_debug_length", _hs_type_real },
	{ "collision_debug_width", _hs_type_real },
	{ "collision_debug_height", _hs_type_real },
	{ "collision_debug_phantom_bsp", _hs_type_boolean },
	{ "collision_log_render", _hs_type_boolean },
	{ "collision_log_detailed", _hs_type_boolean },
	{ "collision_log_extended", _hs_type_boolean },
	{ "collision_log_totals_only", _hs_type_boolean },
	{ "collision_log_time", _hs_type_boolean },
	{ "debug_obstacle_path", _hs_type_boolean },
	{ "debug_obstacle_path_on_failure", _hs_type_boolean },
	{ "debug_obstacle_path_start_point_x", _hs_type_real },
	{ "debug_obstacle_path_start_point_y", _hs_type_real },
	{ "debug_obstacle_path_start_surface_index", _hs_type_long_integer },
	{ "debug_obstacle_path_goal_point_x", _hs_type_real },
	{ "debug_obstacle_path_goal_point_y", _hs_type_real },
	{ "debug_obstacle_path_goal_surface_index", _hs_type_long_integer },
	{ "debug_camera", _hs_type_boolean },
	{ "debug_player", _hs_type_boolean },
	{ "debug_structure", _hs_type_boolean },
	{ "debug_bsp", _hs_type_boolean },
	{ "debug_input", _hs_type_boolean },
	{ "debug_permanent_decals", _hs_type_boolean },
	{ "debug_fog_planes", _hs_type_boolean },
	{ "decals", _hs_type_boolean },
	{ "debug_decals", _hs_type_boolean },
	{ "debug_object_lights", _hs_type_boolean },
	{ "debug_lights", _hs_type_boolean },
	{ "debug_biped_physics", _hs_type_boolean },
	{ "debug_biped_skip_update", _hs_type_boolean },
	{ "debug_biped_skip_collision", _hs_type_boolean },
	{ "debug_biped_limp_body_disable", _hs_type_boolean },
	{ "debug_collision_skip_objects", _hs_type_boolean },
	{ "debug_collision_skip_vectors", _hs_type_boolean },
	{ "debug_material_effects", _hs_type_boolean },
	{ "weather", _hs_type_boolean },
	{ "breakable_surfaces", _hs_type_boolean },
	{ "decals", _hs_type_boolean },
	{ "profile_graph", _hs_type_boolean },
	{ "profile_display", _hs_type_boolean },
	{ "profile_timebase_ticks", _hs_type_boolean },
	{ "profile_dump_frames", _hs_type_boolean },
	{ "profile_dump_lost_frames", _hs_type_boolean },
	{ "recover_saved_games_hack", _hs_type_boolean },
	{ "radiosity_quality", _hs_type_short_integer },
	{ "radiosity_step_count", _hs_type_short_integer },
	{ "radiosity_lines", _hs_type_boolean },
	{ "radiosity_normals", _hs_type_boolean },
	{ "structures_use_pvs_for_vs", _hs_type_boolean },
	{ "debug_texture_cache", _hs_type_boolean },
	{ "debug_detail_objects", _hs_type_boolean },
	{ "ai_render", _hs_type_boolean },
	{ "ai_render_all_actors", _hs_type_boolean },
	{ "ai_render_inactive_actors", _hs_type_boolean },
	{ "ai_render_lineoffire_crouching", _hs_type_boolean },
	{ "ai_render_lineoffire", _hs_type_boolean },
	{ "ai_render_lineofsight", _hs_type_boolean },
	{ "ai_render_ballistic_lineoffire", _hs_type_boolean },
	{ "ai_render_encounter_activeregion", _hs_type_boolean },
	{ "ai_render_vision_cones", _hs_type_boolean },
	{ "ai_render_current_state", _hs_type_boolean },
	{ "ai_render_detailed_state", _hs_type_boolean },
	{ "ai_render_props", _hs_type_boolean },
	{ "ai_render_props_web", _hs_type_boolean },
	{ "ai_render_props_no_friends", _hs_type_boolean },
	{ "ai_render_props_target_weight", _hs_type_boolean },
	{ "ai_render_props_unreachable", _hs_type_boolean },
	{ "ai_render_props_unopposable", _hs_type_boolean },
	{ "ai_render_idle_look", _hs_type_boolean },
	{ "ai_render_support_surfaces", _hs_type_boolean },
	{ "ai_render_recent_damage", _hs_type_boolean },
	{ "ai_render_threats", _hs_type_boolean },
	{ "ai_render_emotions", _hs_type_boolean },
	{ "ai_render_audibility", _hs_type_boolean },
	{ "ai_render_aiming_vectors", _hs_type_boolean },
	{ "ai_render_secondary_looking", _hs_type_boolean },
	{ "ai_render_targets", _hs_type_boolean },
	{ "ai_render_targets_last_visible", _hs_type_boolean },
	{ "ai_render_states", _hs_type_boolean },
	{ "ai_render_vitality", _hs_type_boolean },
	{ "ai_render_active_cover_seeking", _hs_type_boolean },
	{ "ai_render_evaluations", _hs_type_boolean },
	{ "ai_render_pursuit", _hs_type_boolean },
	{ "ai_render_shooting", _hs_type_boolean },
	{ "ai_render_trigger", _hs_type_boolean },
	{ "ai_render_projectile_aiming", _hs_type_boolean },
	{ "ai_render_aiming_validity", _hs_type_boolean },
	{ "ai_render_speech", _hs_type_boolean },
	{ "ai_render_teams", _hs_type_boolean },
	{ "ai_render_player_ratings", _hs_type_boolean },
	{ "ai_render_spatial_effects", _hs_type_boolean },
	{ "ai_render_firing_positions", _hs_type_boolean },
	{ "ai_render_gun_positions", _hs_type_boolean },
	{ "ai_render_burst_geometry", _hs_type_boolean },
	{ "ai_render_vehicle_avoidance", _hs_type_boolean },
	{ "ai_render_vehicles_enterable", _hs_type_boolean },
	{ "ai_render_melee_check", _hs_type_boolean },
	{ "ai_render_dialogue_variants", _hs_type_boolean },
	{ "ai_render_grenade_decisions", _hs_type_boolean },
	{ "ai_render_danger_zones", _hs_type_boolean },
	{ "ai_render_charge_decisions", _hs_type_boolean },
	{ "ai_render_control", _hs_type_boolean },
	{ "ai_render_activation", _hs_type_boolean },
	{ "ai_render_paths", _hs_type_boolean },
	{ "ai_render_paths_selected_only", _hs_type_boolean },
	{ "ai_render_paths_destination", _hs_type_boolean },
	{ "ai_render_paths_current", _hs_type_boolean },
	{ "ai_render_paths_failed", _hs_type_boolean },
	{ "ai_render_paths_raw", _hs_type_boolean },
	{ "ai_render_paths_smoothed", _hs_type_boolean },
	{ "ai_render_paths_avoided", _hs_type_boolean },
	{ "ai_render_paths_avoidance_segment", _hs_type_short_integer },
	{ "ai_render_paths_avoidance_obstacles", _hs_type_boolean },
	{ "ai_render_paths_avoidance_search", _hs_type_boolean },
	{ "ai_render_paths_nodes", _hs_type_boolean },
	{ "ai_render_paths_nodes_all", _hs_type_boolean },
	{ "ai_render_paths_nodes_polygons", _hs_type_boolean },
	{ "ai_render_paths_nodes_costs", _hs_type_boolean },
	{ "ai_render_paths_nodes_closest", _hs_type_boolean },
	{ "ai_render_player_aiming_blocked", _hs_type_boolean },
	{ "ai_render_vector_avoidance", _hs_type_boolean },
	{ "ai_render_vector_avoidance_rays", _hs_type_boolean },
	{ "ai_render_vector_avoidance_sense_t", _hs_type_boolean },
	{ "ai_render_vector_avoidance_avoid_t", _hs_type_boolean },
	{ "ai_render_vector_avoidance_clear_time", _hs_type_boolean },
	{ "ai_render_vector_avoidance_weights", _hs_type_boolean },
	{ "ai_render_vector_avoidance_objects", _hs_type_boolean },
	{ "ai_render_vector_avoidance_intermediate", _hs_type_boolean },
	{ "ai_render_postcombat", _hs_type_boolean },
	{ "ai_print_pursuit_checks", _hs_type_boolean },
	{ "ai_print_rules", _hs_type_boolean },
	{ "ai_print_rule_values", _hs_type_boolean },
	{ "ai_print_major_upgrade", _hs_type_boolean },
	{ "ai_print_respawn", _hs_type_boolean },
	{ "ai_print_evaluation_statistics", _hs_type_boolean },
	{ "ai_print_communication", _hs_type_boolean },
	{ "ai_print_communication_player", _hs_type_boolean },
	{ "ai_print_vocalizations", _hs_type_boolean },
	{ "ai_print_placement", _hs_type_boolean },
	{ "ai_print_speech", _hs_type_boolean },
	{ "ai_print_speech_timers", _hs_type_boolean },
	{ "ai_print_allegiance", _hs_type_boolean },
	{ "ai_print_lost_speech", _hs_type_boolean },
	{ "ai_print_migration", _hs_type_boolean },
	{ "ai_print_automatic_migration", _hs_type_boolean },
	{ "ai_print_scripting", _hs_type_boolean },
	{ "ai_print_surprise", _hs_type_boolean },
	{ "ai_print_command_lists", _hs_type_boolean },
	{ "ai_print_damage_modifiers", _hs_type_boolean },
	{ "ai_print_secondary_looking", _hs_type_boolean },
	{ "ai_print_oversteer", _hs_type_boolean },
	{ "ai_print_conversations", _hs_type_boolean },
	{ "ai_print_killing_sprees", _hs_type_boolean },
	{ "ai_print_acknowledgement", _hs_type_boolean },
	{ "ai_print_unfinished_paths", _hs_type_boolean },
	{ "ai_print_bsp_transition", _hs_type_boolean },
	{ "ai_print_uncovering", _hs_type_boolean },
	{ "ai_profile_disable", _hs_type_boolean },
	{ "ai_profile_random", _hs_type_boolean },
	{ "ai_show", _hs_type_boolean },
	{ "ai_show_stats", _hs_type_boolean },
	{ "ai_show_actors", _hs_type_boolean },
	{ "ai_show_swarms", _hs_type_boolean },
	{ "ai_show_paths", _hs_type_boolean },
	{ "ai_show_line_of_sight", _hs_type_boolean },
	{ "ai_show_prop_types", _hs_type_boolean },
	{ "ai_show_sound_distance", _hs_type_boolean },
	{ "ai_debug_fast_los", _hs_type_boolean },
	{ "ai_debug_oversteer_disable", _hs_type_boolean },
	{ "ai_debug_evaluate_all_positions", _hs_type_boolean },
	{ "ai_debug_path", _hs_type_boolean },
	{ "ai_debug_path_start_freeze", _hs_type_boolean },
	{ "ai_debug_path_end_freeze", _hs_type_boolean },
	{ "ai_debug_path_flood", _hs_type_boolean },
	{ "ai_debug_path_maximum_radius", _hs_type_real },
	{ "ai_debug_path_attractor", _hs_type_boolean },
	{ "ai_debug_path_attractor_radius", _hs_type_real },
	{ "ai_debug_path_attractor_weight", _hs_type_real },
	{ "ai_debug_path_accept_radius", _hs_type_real },
	{ "ai_debug_ballistic_lineoffire_freeze", _hs_type_boolean },
	{ "ai_debug_communication_random_disabled", _hs_type_boolean },
	{ "ai_debug_communication_timeout_disabled", _hs_type_boolean },
	{ "ai_debug_communication_unit_repeat_disabled", _hs_type_boolean },
	{ "ai_debug_communication_focus_enable", _hs_type_boolean },
	{ "ai_debug_blind", _hs_type_boolean },
	{ "ai_debug_deaf", _hs_type_boolean },
	{ "ai_debug_invisible_player", _hs_type_boolean },
	{ "ai_debug_ignore_player", _hs_type_boolean },
	{ "ai_debug_flee_always", _hs_type_boolean },
	{ "ai_debug_force_all_active", _hs_type_boolean },
	{ "ai_debug_disable_wounded_sounds", _hs_type_boolean },
	{ "ai_debug_force_vocalizations", _hs_type_boolean },
	{ "ai_debug_force_crouch", _hs_type_boolean },
	{ "ai_debug_path_disable_smoothing", _hs_type_boolean },
	{ "ai_debug_path_disable_obstacle_avoidance", _hs_type_boolean },
	{ "ai_fix_defending_guard_firing_positions", _hs_type_boolean },
	{ "ai_fix_actor_variants", _hs_type_boolean },
	{ "controls_enable_crouch", _hs_type_boolean },
	{ "controls_swapped", _hs_type_boolean },
	{ "controls_enable_doubled_spin", _hs_type_boolean },
	{ "controls_swap_doubled_spin_state", _hs_type_boolean },
	{ "player0_look_yaw_rate", _hs_type_real },
	{ "player1_look_yaw_rate", _hs_type_real },
	{ "player2_look_yaw_rate", _hs_type_real },
	{ "player3_look_yaw_rate", _hs_type_real },
	{ "player0_look_pitch_rate", _hs_type_real },
	{ "player1_look_pitch_rate", _hs_type_real },
	{ "player2_look_pitch_rate", _hs_type_real },
	{ "player3_look_pitch_rate", _hs_type_real },
	{ "player_autoaim", _hs_type_boolean },
	{ "player_magnetism", _hs_type_boolean },
	{ "debug_player_teleport", _hs_type_boolean },
	{ "texture_cache_graph", _hs_type_boolean },
	{ "texture_cache_list", _hs_type_boolean },
	{ "director_camera_switch_fast", _hs_type_boolean },
	{ "debug_recording", _hs_type_boolean },
	{ "debug_recording_newlines", _hs_type_short_integer },
	{ "debug_player_color", _hs_type_short_integer },
	{ "debug_framerate", _hs_type_boolean },
	{ "display_framerate", _hs_type_boolean },
	{ "display_vblank_deltas", _hs_type_boolean },
	{ "framerate_throttle", _hs_type_boolean },
	{ "framerate_lock", _hs_type_boolean },
	{ "display_precache_progress", _hs_type_boolean },
	{ "debug_game_save", _hs_type_boolean },
	{ "allow_out_of_sync", _hs_type_boolean },
	{ "global_connection_dont_timeout", _hs_type_boolean },
	{ "find_all_fucked_up_shit", _hs_type_boolean },
	{ "run_game_scripts", _hs_type_boolean },
};
